### ISSUE TITLE
3. Useless buttons

### ISSUE THREAD

**Issue by Riva77** [AngelMaharjan/RestaurantManagement#32]
In the home page there are two useless button i.e. favorite and a button with eye symbol. We don't need those button and those are not clickable either. Also the food items present in home page are not clickable too. 
![image](https://github.com/AngelMaharjan/RestaurantManagement/assets/126968387/10d1627e-2f8e-429c-a3e1-2fa1b91252d6)

**Comment by onlynik0** [comment]
completed
