### ISSUE TITLE
7. User should be directed into home page after adding food in cart. 

### ISSUE THREAD

**Issue by Riva77** [AngelMaharjan/RestaurantManagement#36]
Because the my cart option is only available in home page. Either the my cart option can be added in menu page or the user should be directly redirect in home page. 
![image](https://github.com/AngelMaharjan/RestaurantManagement/assets/126968387/f182aba1-69b2-4245-8f1f-3227d3213c01)

**Comment by rozanDai** [comment]
I've solved this task..!!
