### ISSUE TITLE
8. Name of button

### ISSUE THREAD

**Issue by Riva77** [AngelMaharjan/RestaurantManagement#37]
The name of this button should be change password not reset password. 
![image](https://github.com/AngelMaharjan/RestaurantManagement/assets/126968387/d1bacfde-8cca-4f79-a937-19b39fabea95)

**Comment by kaushalpapnai** [comment]
Hi 

I'm a newbie to the open source community, and I'm excited to get started by contributing to your project. I'm interested in making some changes to the CSS of the web page, but before I do, I wanted to check with you to see if this is something that you'd be interested in.

If so, I'd love to discuss my ideas with you and make sure they align with the project's goals and design standards. I'm open to feedback and suggestions as I want to learn and grow as a contributor.

**Comment by onlynik0** [comment]
Completed
